### ISSUE TITLE
Segfault 11 on macOS

### ISSUE THREAD

**Issue by ameturpoet** [Sorrow446/KHInsider-Downloader#1]
Giving the Mac version of this script execution permissions on an Apple Silicon will cause it to fail instantly when running it, giving this error:
`Segmentation fault: 11`

**Comment by ameturpoet** [comment]
On Windows 10, I also see this error immediately when running the exe:
```
panic: Failed to parse config/args.
open config.json: The system cannot find the file specified.

goroutine 1 [running]:
main.handleErr({0x34c51d, 0x1c}, {0x3cf1e0?, 0xc00010f410?}, 0x1)
        G:/go/kh/main.go:90 +0xc5
main.main()
        G:/go/kh/main.go:455 +0x85
```

**Comment by Sorrow446** [comment]
https://github.com/Sorrow446/Nugs-Downloader/issues/9
You need to build it yourself.
`./go build main.go structs.go`

**Comment by ameturpoet** [comment]
Thanks for the tip - I built the "main" script, but it gives me the following error whenever I run it, with or without arguments or input:

```
panic: Failed to auth.
400 Bad Request

goroutine 1 [running]:
main.handleErr({0x100ea0dc7, 0xf}, {0x100fa2fa0?, 0x1400011b1c0?}, 0x1)
	/Users/victoria/Downloads/Nugs-Downloader-main/main.go:113 +0xc0
main.main()
	/Users/victoria/Downloads/Nugs-Downloader-main/main.go:1306 +0xdc
```

**Comment by ameturpoet** [comment]
Also the downloader seems to fail with single-word game IDs - try URLs with a single word after /album/ in the URL and it will always say the URL is invalid

**Comment by Sorrow446** [comment]
You're building my Nugs downloader, not this KHInsider downloader haha.

I can fix the invalid URL problem. Could you send an example URL?

**Comment by ameturpoet** [comment]
Whoops, re-built with the right software this time, sorry ><
But I still see the issue on both macOS and Windows for single-word urls - here are some example URLs:
https://downloads.khinsider.com/game-soundtracks/album/flower
https://downloads.khinsider.com/game-soundtracks/album/actraiser

**Comment by Sorrow446** [comment]
Oh. Fixed, sorry about that. You can just redownload the source and build again.
https://github.com/Sorrow446/KHInsider-Downloader/commit/fdf9d6c48d4a749bb152a1a6e62d3881d14b736e

**Comment by ameturpoet** [comment]
Thank you so much for such a quick fix! Hope you're having a happy new year! ^_^
