### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by EzekialSA** [Sorrow446/KHInsider-Downloader#2]
when attempting /game-soundtracks/album/wario-land-iv

Config:
{
    "format": 4,
    "outPath": "D:\\Temp\\album",
    "diskNumPrefix": "Disk "
}

Command:
khi_dl_x64.exe https://downloads.khinsider.com/game-soundtracks/album/wario-land-iv

Output:

 _____ _____ _____         _   _            ____                _           _
|  |  |  |  |     |___ ___|_|_| |___ ___   |    \ ___ _ _ _ ___| |___ ___ _| |___ ___
|    -|     |-   -|   |_ -| | . | -_|  _|  |  |  | . | | | |   | | . | .'| . | -_|  _|
|__|__|__|__|_____|_|_|___|_|___|___|_|    |____/|___|_____|_|_|_|___|__,|___|___|_|

Album 1 of 1:
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main.extractMeta({0xc00001a140?, 0x44?}, {0xc00001a177, 0xd})
        G:/go/kh/main.go:304 +0x5ba
main.main()
        G:/go/kh/main.go:471 +0x267
        
Numerous other albums succeeded without issue, just seems to be an error with metadata on the album maybe?

**Comment by Sorrow446** [comment]
Seems fine now. Must've been running outdated binaries.
