### ISSUE TITLE
Failed to download track. 404 Not Found (Mac)

### ISSUE THREAD

**Issue by pepplerock** [Sorrow446/KHInsider-Downloader#3]
ok you will have to forgive me for not being super skilled with this sorry! this has been working for a long time for me and suddenly stopped working a couple months ago, i hope khinsider didn't break it. i'm on an M1 mac ventura 13.3.1
here is what i did step by step:

download the repo source code
change config.json to the following:
```
{
    "format": 4,
    "outPath": "/my/path/",
    "diskNumPrefix": "Disk "
}
```
open terminal and cd to the folder
`go build main.go structs.go`
then `./main https://downloads.khinsider.com/game-soundtracks/album/hades-original-soundtrack`
it starts out like this:
```
Album 1 of 1:
Hades: Original Soundtrackinfo
Downloading track 1 of 30: No Escape - M4A
Failed to download track.
404 Not Found
```
then for every track it gives me the Failed to download track. 404 Not Found error. it also seems to think the album is "Hades: Original Soundtrack**info**" rather than the actual name which is "Hades: Original Soundtrack." it creates a folder in the appropriate directory that is titled "Hades: Original Soundtrackinfo" and has a bunch of zero-byte audio files in it.

i get this same error if i run `go run main.go structs.go  https://downloads.khinsider.com/game-soundtracks/album/hades-original-soundtrack` in the KHInsider-Downloader-main folder. this happens with every url i've tried, regardless of file format.

am i doing something wrong? this method used to work for me. also please respond with like. step by step instructions lmao i am not very well-versed in running command-line programs

**Comment by Sorrow446** [comment]
I've only just seen this, sorry. They've probably patched it, haven't updated this in ~10 months. Will fix it if it's not too much trouble. Nah, you're using the right commands.

**Comment by Sorrow446** [comment]
Fixed. https://github.com/Sorrow446/KHInsider-Downloader/commit/1026131ca3af11b43b0bbc394580bacdda3131a1

Should've reached out to me over Discord and I could've had this fixed much quicker :p.
