### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by KyleStilkey** [Sorrow446/KHInsider-Downloader#4]
Unable to download anything, just results in a 404 error files not found.

**Comment by Sorrow446** [comment]
It's fine now. Was a site issue.

**Comment by KyleStilkey** [comment]
OK I'll give it a shot later today and see if any issues come up.

**Comment by Sorrow446** [comment]
If it's still an issue, it'll be because you're running the outdated binary. Run from src code or use this I just built: https://workupload.com/file/dyZXmZdS8aJ

**Comment by KyleStilkey** [comment]
So far so good, dropped in a few links and it had no problem at all!
